### ISSUE TITLE
error occurred while creating a new issues

### ISSUE THREAD

**Issue by codyliou** [guilhermenoronha/redmine_send_mails#2]
hi, 
An error occurred while creating a new issues

Started GET "/projects/test/issues/new" for 127.0.0.1 at 2013-10-30 13:46:23 +08
00
Processing by IssuesController#new as HTML
  Parameters: {"project_id"=>"test"}
  Current user: admin (id=1)
  Rendered issues/_form_custom_fields.html.erb (5.0ms)
  Rendered issues/_attributes.html.erb (23.0ms)
  Rendered issues/_form.html.erb (38.0ms)
  Rendered attachments/_form.html.erb (3.0ms)
  Rendered plugins/redmine_send_mails/app/views/issues/new.html.erb within layou
ts/base (247.0ms)
Completed 500 Internal Server Error in 280ms

ActionView::Template::Error (undefined method `link_to_remote' for #<#<Class:0x7
e3e5f8>:0x6616020>):
    26:         <%= watchers_checkboxes(@issue, @available_watchers) %>
    27:       </span>
    28:       <span class="search_for_watchers">
    29:       <%= link_to_remote l(:label_search_for_watchers),
    30:                    :url => {:controller => 'watchers', :action => 'new',
 :project_id => @issue.project},
    31:                    :method => 'get' %>
    32:       </span>
  app/helpers/application_helper.rb:948:in`labelled_form_for'
  app/controllers/issues_controller.rb:134:in `block (2 levels) in new'
##   app/controllers/issues_controller.rb:133:in `new'

Environment:
  Redmine version                2.3.3.stable
  Ruby version                   2.0.0-p247 (2013-06-27) [i386-mingw32]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               SQLite
Redmine plugins:
  enhanced_queries               0.2
  redmine_send_mails             0.0.2

**Comment by guilhermenoronha** [comment]
Hello codyliou,

This plugin was developed inside of redmine 2.0.x. I'm opening a branch to adapt this plugin to 2.3.x. When it be available, I'll send a message to you. Thanks for feedback.

**Comment by guilhermenoronha** [comment]
A new branch was created 0.2.23x (to work on redmine 2.3.x). Please get this new branch and check if your issue was resolved. In case affirmative, please close the issue. Thanks.
